name: marker
description: A renderer (printer) for the markdown library. Renders the parsed AST back into markdown.
version: 0.2.1
homepage: https://github.com/f3ath/marker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  markdown: ^4.0.0

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.11.0
  coverage: ^1.0.1
  check_coverage: ^0.0.1
