name: markdown_renderer
description: A renderer (printer) for the markdown library. Saves the parsed AST basck into markdown.
version: 0.0.1
# homepage: https://www.example.com
# author: f3ath <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  markdown: ^2.0.0

dev_dependencies:
  test: ^1.0.0
