name: marker
description: A renderer (printer) for the markdown library. Saves the parsed AST basck into markdown.
version: 0.0.2
author: "Alexey Karapetov <karapetov@gmail.com>"
homepage: https://github.com/f3ath/marker

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  markdown: ^2.0.0

dev_dependencies:
  test: ^1.0.0
