name: marker
description: A renderer (printer) for the markdown library. Saves the parsed AST back into markdown.
version: 0.1.1
homepage: https://github.com/f3ath/marker

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  markdown: ^3.0.0

dev_dependencies:
  test: ^1.9.0
  pedantic: ^1.9.0
